# ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- #
# This file is to replicate the response of a database response.
# ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- #
# TODO: replace this with the database

sites = {
    'lulz': {'url': 'http://privacy.aol.com/privacy-policy/',
        'xpath': '//*[@id="doesnotexist"]'},
    '500px PP': {'url': 'http://500px.com/privacy',
        'xpath': '//*[@id="terms"]'},
    '500px ToS': {'url': 'http://500px.com/terms',
        'xpath': '//*[@id="terms"]'},
	'Amazon Bill of Rights': {'url': 'http://www.amazon.com/gp/help/customer/display.html?nodeId=508092',
		'xpath': '/html/body/table/tbody/tr/td[2]'},
	'Amazon CoU': {'url': 'http://www.amazon.com/gp/help/customer/display.html?nodeId=508088',
		'xpath': '/html/body/table/tbody/tr/td[2]'},
	'Amazon Privacy Notice': {'url': 'http://www.amazon.com/gp/help/customer/display.html?nodeId=468496',
		'xpath': '/html/body/table/tbody/tr/td[2]'},
    'AOL PP': {'url': 'http://privacy.aol.com/privacy-policy/',
        'xpath': '//*[@id="article"]'},
    'AOL ToS': {'url': 'http://legal.aol.com/terms-of-service/full-terms/',
        'xpath': '//*[@id="article"]'},
	'craigslist PP': {'url': 'http://www.craigslist.org/about/privacy_policy',
		'xpath': '/html/body/div/div[2]/div'},
	'craigslist ToU': {'url': 'http://www.craigslist.org/about/terms.of.use',
		'xpath': '/html/body/blockquote'},
    'Digg PP': {'url': 'http://about.digg.com/privacy',
        'xpath': '/html/body/div[2]/div/div/div'},
    'Digg ToS': {'url': 'http://about.digg.com/terms-use',
        'xpath': '/html/body/div[2]/div/div/div'},
	'Disney Go Communications Choices': {'url': 'http://corporate.disney.go.com/corporate/pp_communication-choices.html',
		'xpath': '//*[@id="TERMS"]'},
	'Disney Go Kids\' PP': {'url': 'http://corporate.disney.go.com/corporate/kids.html',
		'xpath': '//*[@id="TERMS"]'},
	'Disney Go Notice to California Residents': {'url': 'http://corporate.disney.go.com/corporate/pp_california.html',
		'xpath': '//*[@id="TERMS"]'},
	'Disney Go Online Tracking and Advertising': {'url': 'http://corporate.disney.go.com/corporate/pp_online-tracking-advertising.html',
		'xpath': '//*[@id="TERMS"]'},
	'Disney Go PP': {'url': 'http://corporate.disney.go.com/corporate/pp.html',
		'xpath': '//*[@id="TERMS"]'},
	'Disney Go ToU': {'url': 'http://corporate.disney.go.com/corporate/terms.html',
		'xpath': '//*[@id="TERMS"]'},
    'DuckDuckGo': {'url': 'https://duckduckgo.com/privacy.html',
        'xpath': '//*[@id="content_internal"]'},
    'Facebook PP': {'url': 'http://www.facebook.com/full_data_use_policy',
        'xpath': '//*[@id="contentArea"]'},
    'Facebook ToS': {'url': 'http://www.facebook.com/terms.php',
        'xpath': '/html/body/div[3]/div/div/div/div[2]/div/div'},
	'eBay PP': {'url': 'http://pages.ebay.com/help/policies/privacy-policy.html',
		'xpath': '/html/body/div/div/table[2]/tbody/tr[3]/td[3]/table/tbody/tr/td/div/form/div/div[2]'},
	'eBay User Agreement': {'url': 'http://pages.ebay.com/help/policies/user-agreement.html',
		'xpath': '/html/body/div/div/table[2]/tbody/tr[3]/td[3]/table/tbody/tr/td/div/form/div/div[2]'},
    'Google PP': {'url': 'http://www.google.com/intl/en/policies/privacy/',
        'xpath': '/html/body/div[3]/div[2]'},
    'Google ToS': {'url': 'https://www.google.com/intl/en/policies/terms/',
        'xpath': '/html/body/div[3]/div[2]'},
	'LinkedIn PP': {'url': 'http://www.linkedin.com/static?key=privacy_policy',
		'xpath': '/html/body/div[2]/div[2]/div[2]/div'},
	'LinkedIn User Agreement': {'url': 'http://www.linkedin.com/static?key=user_agreement',
		'xpath': '/html/body/div[2]/div[2]/div[2]/div'},
	'Microsoft Online Privacy Statement': {'url': 'http://privacy.microsoft.com/en-us/fullnotice.mspx',
		'xpath': '/html/body/div[2]/div'},
	'Microsoft Services Agreement': {'url': 'http://windows.microsoft.com/en-US/windows-live/microsoft-service-agreement',
		'xpath': '//*[@id="aspnetForm"]'},
    'MITx ToS': {'url': 'https://6002x.mitx.mit.edu/t/tos.html', 
        'xpath': '/html/body/section/div'},
    'MITx PP': {'url': 'https://6002x.mitx.mit.edu/t/privacy.html',
        'xpath': '/html/body/section/div'},
    'MITx Copyright': {'url': 'https://6002x.mitx.mit.edu/t/copyright.html',
        'xpath': '/html/body/section/div'},
    'MITx Honor Code': {'url': 'https://6002x.mitx.mit.edu/t/honor.html',
        'xpath': '/html/body/section/div'},
	'MSN Privacy Supplement': {'url': 'http://privacy.microsoft.com/en-us/msn.mspx',
		'xpath': '/html/body/div[2]/div'},
	'msnbc.com Terms & Conditions': {'url': 'http://www.msnbc.msn.com/id/3303540/ns/about/t/terms-conditions/',
		'xpath': '/html/body/div[5]/div/div[3]/div[2]/div'},
    'NewEgg TaC': {'url': 'http://www.newegg.com/Info/AllTermsAndConditions.aspx',
        'xpath': '//*[@id="bcaInfoContainer"]'},
	'Pinterest Acceptable Use Policy': {'url': 'http://pinterest.com/about/use/',
		'xpath': '//*[@id="legal"]'},
	'Pinterest PP': {'url': 'http://pinterest.com/about/privacy/',
		'xpath': '//*[@id="legal"]'},
	'Pinterest ToS': {'url': 'http://pinterest.com/about/terms/',
		'xpath': '//*[@id="legal"]'},
    'reddit PP': {'url': 'http://www.reddit.com/help/privacypolicy',
        'xpath': '//*[@id="content"]'},
    'reddit ToS': {'url': 'http://www.reddit.com/help/useragreement',
        'xpath': '//*[@id="content"]'},
    'Safari Books Online PP': {'url': 'http://www.safaribooksonline.com/privacy-policy',
        'xpath': '/html/body/div[3]/div/div/div[3]/div/div/div/div/div/div/div'},
    'Safari Books Online ToS': {'url': 'http://www.safaribooksonline.com/terms-service',
        'xpath': '//*[@id="internal_content"]'},
	'Wikimedia PP': {'url': 'https://wikimediafoundation.org/wiki/Privacy_policy',
		'xpath': '//*[@id="mw-content-text"]'},
	'Wikimedia ToU': {'url': 'http://wikimediafoundation.org/wiki/Terms_of_Use',
		'xpath': '//*[@id="mw-content-text"]'},
    'Twitter PP': {'url': 'https://twitter.com/privacy',
        'xpath': '/html/body/div[2]/div/div'},
    'Twitter ToS': {'url': 'https://twitter.com/tos',
        'xpath': '/html/body/div[2]/div/div'},
    'Yahoo': {'url': 'http://info.yahoo.com/legal/us/yahoo/utos/utos-173.html',
        'xpath': '/html/body/div/div[4]/div/div/div'},
    }

